### ISSUE TITLE
didSelectRowAtIndexPath Delegate / hide Slide Menu

### ISSUE THREAD

**Issue by rary44** [teodorpatras/SideMenuController#15]
Hello

Is it possible to create the whole project programmatically (nib files without storyboard)?

i'm facing a problem with step 4 👍 
```
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
    sideMenuController?.embedCenterController(someUIViewControllerInstance)
}

```
When i select any cell [view controller] more than one time , it's shows the slide menu table quickly and it disappear , why is that ?

Regards

**Comment by teodorpatras** [comment]
Hi, can you upload an example project where you can reproduce this issue?

**Comment by rary44** [comment]
[SlideMenu.zip](https://github.com/teodorpatras/SideMenuController/files/340875/SlideMenu.zip)
Please Find it above

**Comment by teodorpatras** [comment]
this is an empty project.. i meant a project with some code that reproduces the issue...

**Comment by rary44** [comment]
i upload it again please check it
i think the problem with the animation

**Comment by teodorpatras** [comment]
First of all, thank you for a project that does not compile. The problem is not with the animation, the problem is with how you "architected" the code. You have an array of view controllers from which you exchange the view controllers among each other. The problem is as follows:

when you select the same index, you make a transition to the same view controller that is visible on screen (which btw, should not happen, you should put a `guard indexPath != previous index else { return }`) and because you pass in the same view controller that is already embedded to the function `embed(centerViewController:` the animation gets lost because there is one single view which should be animated both off and on screen. 

Conclusion: 

Don't embed the same controller that is already on screen.

P.S: update to version `0.1.3`

**Comment by rary44** [comment]
Sorry didn't notice that i fix the project 
[SlideMenu 3.zip](https://github.com/teodorpatras/SideMenuController/files/358638/SlideMenu.3.zip)

could you explain in the code please , i try to put (guard indexPath != previousIndex else { return }) and it didn't work
  ```
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        if let index = previousIndex {
            tableView.deselectRowAtIndexPath(index, animated: true)
        }
        
    let selectedSection = indexPath.section
        let nc1 : UINavigationController?
   
        switch(selectedSection) {
        case 0:
            
            guard indexPath != previousIndex else { return }
             nc1 = UINavigationController(rootViewController: tabOfChildViewController[0])
             nc1!.navigationController?.navigationBar.barTintColor = UIColor.blueColor()
             
             sideMenuController?.embedCenterController(nc1!)
        case 1:
            switch(indexPath.row) {
            case 0:
               let nc2 = UINavigationController(rootViewController: tabOfChildViewController[1])
               nc2.navigationController?.navigationBar.barTintColor = UIColor.blueColor()
               
               sideMenuController?.embedCenterController(nc2)
            case 1:
                let nc2 = UINavigationController(rootViewController: tabOfChildViewController[2])
                nc2.navigationController?.navigationBar.barTintColor = UIColor.blueColor()
                
                sideMenuController?.embedCenterController(nc2)
                
                default: fatalError("Unknown section")
            }
            
                    
        default: fatalError("Unknown number of sections")
        }

 
    }
```
Regards
