### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by daniel-mohemian** [teodorpatras/SideMenuController#162]
@teodorpatras: Since the[ last change](https://github.com/teodorpatras/SideMenuController/commit/8ed33ee4a7b5897e4978d768e5da35afd27f0570) that made it's way to master is over a year old by now, I was wondering if you plan on continuing maintaining this project. This might be interesting information for people comparing different side menu implementations and choosing which one to integrate. If this project is no longer maintained, I think we should mention that in the readme.

**Comment by teodorpatras** [comment]
The release for Swift 4.x will be available soon, when I find some free time. Since there are no other core contributors than me, and most of the open PRs are unmergeable, the updates are coming at a much lower frequency than before. If you want to be proactive, you are more than welcome to open a PR and tag me there.

**Comment by daniel-mohemian** [comment]
Ok good to know! 👍
