### ISSUE TITLE
Swiping not working

### ISSUE THREAD

**Issue by mobinzk** [teodorpatras/SideMenuController#18]
Seems that only panning works and using:
```
SideMenuController.preferences.interaction.panningEnabled = false
SideMenuController.preferences.interaction.swipingEnabled = true
```

Doesn't enable swiping only

**Comment by teodorpatras** [comment]
If the side menu panel is positioned under the center panel, you don't need there is no swipe gesture created because you have the pan gesture so it is redundant to have both. The swipe gesture recognizer is only created for when the side panel is above the center panel. When the side panel is above the center panel, the pan gesture is on the side panel, and the swipe is on the center panel overlay.

**Comment by teodorpatras** [comment]
I'll update the readme file.

**Comment by mobinzk** [comment]
Thanks for your response but in my example, I have a slider in my view which makes the user experience really bad if I keep pan gesture enabled. I want to have swipe from edge and not panning to resolve this issue.

Hope this makes sense

**Comment by teodorpatras** [comment]
Hmm, I see... I am going to be replacing `UIPanGestureRecognizer` with `UIScreenEdgePanGestureRecognizer` so then the panning will only work when started from the edge of the screen. Will release a new version next days. Stay tuned :)

**Comment by mobinzk** [comment]
That's great thanks, looking forward to that.

**Comment by FouadRaheb** [comment]
+1, can we also make it that panning stops after presenting/pushing another view from center view?
